# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.8"

os: linux
dist: focal

addons:
  sonarcloud:
    organization: vinivioti
    token: ${SONAR_TOKEN}
     
jobs:
  include:
    - stage: Build & Tests
      name: "Unit Test, Quality & Security"
      
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: labdevopsvinissius
        on:
          branch: main

    - stage: STG TEST
      script:
        - curl https://labdevopsvinissius.herokuapp.com/ | grep Hello || travis_terminate 1;