# Versão do Ubuntu
os: linux
dist: focal

# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.8"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: labdevopsvinissius
  on:
      branch: main
